
import dataApiSidebar from './docs/spec/data/sidebar';
import configuratorSidebar from './docs/spec/configurator/sidebar';
import scimSidebar from './docs/spec/scim/sidebar';
import quotationSidebar from './docs/spec/quotation/sidebar';

export default {
  tutorialSidebar: [{type: 'autogenerated', dirName: 'doc'}],
  apiSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'apis'
    },
    {
      type: 'link',
      href: '../spec/data/odata-service-for-namespace-default',
      label: 'Data API'
    },
    {
      type: 'link',
      href: '../spec/configurator/elfsquad-configurator-api',
      label: 'Configurator'
    },
    {
      type: 'link',
      href: '../spec/scim/scim-api',
      label: 'SCIM'
    },
    {
      type: 'link',
      href: '../spec/quotation/elfsquad-web-quotationapi',
      label: 'Quotation'
    }
  ],
  dataApiSidebar: dataApiSidebar,
  configuratorSidebar: configuratorSidebar,
  scimSidebar: scimSidebar,
  quotationSidebar: quotationSidebar
};
