
import dataApiSidebar from './docs/spec/data/sidebar';
import configuratorSidebar from './docs/spec/configurator/sidebar';
import scimSidebar from './docs/spec/scim/sidebar';
import quotationSidebar from './docs/spec/quotation/sidebar';

export default {
  apiSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'apis'
    }
  ],
  dataApiSidebar: dataApiSidebar,
  configuratorSidebar: configuratorSidebar,
  scimSidebar: scimSidebar,
  quotationSidebar: quotationSidebar,
  guidesSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'guides'
    }
  ],
  customizationSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'customization'
    }
  ],
  archerSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'archer'
    }
  ],
};
