
import configuratorApiSidebar from './docs/spec/configurator/sidebar';
import scimSidebar from './docs/spec/scim/sidebar';
import quotationSidebar from './docs/spec/quotation/sidebar';
import customizationSidebar from './docs/customization/sidebar';
import configuratorSidebar from './docs/configurator/sidebar';

export default {
  apiSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'apis'
    }
  ],
  configuratorSidebar: configuratorSidebar,
  dataApiSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'spec/data'
    }  
  ],
  configuratorApiSidebar: configuratorApiSidebar,
  scimSidebar: scimSidebar,
  quotationSidebar: quotationSidebar,
  guidesSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'guides'
    }
  ],
  customizationSidebar: customizationSidebar,
  archerSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'archer'
    }
  ],
} as SidebarsConfig;
