import configuratorApiSidebar from '../spec/configurator/sidebar';

const sidebar = [
  {
    type: 'autogenerated', 
    dirName: 'configurator'
  },
  {
    type: 'category',
    label: 'Configurator Web API',
    items: configuratorApiSidebar
  }
]

export default sidebar;

