import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    { type: 'doc', id: 'extensions/index' },
    {
      type: 'category', 
      label: 'Getting started',
      items: [
        {
          type: 'autogenerated', 
          dirName: 'extensions/getting-started',
        }
      ]
    },
    {
      type: 'category',
      label: 'Extension components',
      items: [
        {
          type: 'autogenerated',
          dirName: 'extensions/components',
        }
      ]
    },
    {
      type: 'category',
      label: '@elfsquad/cli',
      items: [
        {
          type: 'autogenerated',
          dirName: 'extensions/cli',
        }
      ]
    },
    {
      type: 'doc',
      label: '@elfsquad/custom-scripting',
      id: 'extensions/custom-scripting/index'
    }
  ],
};

export default sidebar.apisidebar;

